### ISSUE TITLE
Create Docs

### ISSUE THREAD

**Issue by hkveeranki** [harry-7/speech-emotion-recognition#10]
Most of the code has incode documentation. But there are no standard docs for the code and the logic behind it. Add the necessary documentation

**Comment by kuruvadattatreya** [comment]
will you please share the base papers or documentation?Thanks in advance.

**Comment by hkveeranki** [comment]
Hi, there are no base papers, all these model architectures are my own. I was busy in the past few days and hence the delay in updating the documentation.

**Comment by hkveeranki** [comment]
Hi, The documentation is available at https://harry-7.github.io/speech-emotion-recognition/html/speechemotionrecognition.html.
