### ISSUE TITLE
Issue facing in lstm_example

### ISSUE THREAD

**Issue by Avi143** [harry-7/speech-emotion-recognition#14]
Dear sir,

I am getting error while executing the lstm_example. 
could you please check once and please let me know if any modifications has to be done.

Thank you. 
![Screenshot from 2019-03-31 16-50-56](https://user-images.githubusercontent.com/26404754/55288442-748c4500-53d5-11e9-91b7-5a395f2a0845.png)

**Comment by hkveeranki** [comment]
Hey, I fixed the bug. Please try with the latest code thanks.
