### ISSUE TITLE
ImportError: cannot import name 'Model' 

### ISSUE THREAD

**Issue by ck0604** [harry-7/speech-emotion-recognition#15]
When running dnn.py 
I'm getting an error as follows: 
Using TensorFlow backend.
Traceback (most recent call last):
    File "dnn.py", line 11, in <module> 
       from . import Model 
ImportError: cannot import name 'Model'

**Comment by deniz-ekiz** [comment]
how to fix this problem?

**Comment by hkveeranki** [comment]
Install the package and try running the example again.
