### ISSUE TITLE
documentation link is down

### ISSUE THREAD

**Issue by SelimDeniz** [harry-7/speech-emotion-recognition#31]
Hi, thanks for the code. The documentation link is broken, could you please update it?

**Comment by coattosintetico** [comment]
It's broken because he updated his username, and the link is a github page with his username in the url. 

The new link is [this](https://hkveeranki.github.io/speech-emotion-recognition/html/main.html).

**Comment by SelimDeniz** [comment]
> It's broken because he updated his username, and the link is a github page with his username in the url.
> 
> The new link is [this](https://hkveeranki.github.io/speech-emotion-recognition/html/main.html).

Thanks!
