### ISSUE TITLE
regarding accuray 

### ISSUE THREAD

**Issue by ramesh720** [harry-7/speech-emotion-recognition#4]
recently i asked you regarding accuracy .
https://github.com/harry-7/speech-emotion-recognition/issues/3
i did multiclassification not binary classification 
Is keras calculates accuracy by sample wise or labels wise ?
just consider 2 samples only.
suppose y_pred=[ [0.35, 0.2, 0.2, 0.25], [0.33, 0.22, 0.18, 0.27] ]
and my t_test= [ [1, 0, 0, 0] , [0, 0, 0, 1] ]
scikit accuracy is 50% because in scikit all labels must be same
what about keras .how it actually calculates.
can you please explain me with exmples. it will help to me a lot

**Comment by hkveeranki** [comment]
@ramesh720, unfortunately I don't have much idea about how keras and scikit learn calculate accuracies. https://github.com/keras-team/keras/issues/9672 can give you a better insight on this. That issue is about the exact same problem you are facing. Can you have a look at it?

**Comment by ramesh720** [comment]
thank you sir.

**Comment by hkveeranki** [comment]
@ramesh720 No problems. I am closing this issue. If you have any further questions, feel free to re open this issue with a comment.
