### ISSUE TITLE
Models accuracy

### ISSUE THREAD

**Issue by ehsanmqn** [harry-7/speech-emotion-recognition#6]
Is there any report about applied models accuracy?

**Comment by hkveeranki** [comment]
Can you elaborate? What do you mean by applied models accuracy?

**Comment by ehsanmqn** [comment]
I mean each model (LSTM, CNN and etc) accuracy on emo-DB. I've just ran the code and got each model accuracy. For now, I have another problem. There isn't any function script to process new speech audios and classify them according to model result. Is there?
I guess your code become more usable if you add reports about it's accuracy on emo-DB and add some examine functions for unclassified audio files.

**Comment by hkveeranki** [comment]
> For now, I have  another problem. There isn't any function script to process new speech  audios and classify them according to model result. Is there?

No there isn't but its a good feature to have. I will add this functionality soon.

>  I guess your code become more usable if you add reports about it's  accuracy on emo-DB.

You already told me that, you got accuracies from each model. Can you incorporate this data into a txt or an .md file and send a pull request?

**Comment by ehsanmqn** [comment]
> > For now, I have  another problem. There isn't any function script to process new speech  audios and classify them according to model result. Is there?
> 
> No there isn't but its a good feature to have. I will add this functionality soon.
> 
> > I guess your code become more usable if you add reports about it's  accuracy on emo-DB.
> 
> You already told me that, you got accuracies from each model. Can you incorporate this data into a txt or an .md file and send a pull request?

Sure, I'll do that soon as possible.

**Comment by kuruvadattatreya** [comment]
when I am trying to execute the code I am getting this error
print 'Accuracy =', self.model.evaluate(x_test, y_test)[1]
                     ^
SyntaxError: invalid syntax.
please explain how to remove the error.Thanks in advance

**Comment by nasirbashak** [comment]
> when I am trying to execute the code I am getting this error
> print 'Accuracy =', self.model.evaluate(x_test, y_test)[1]
> ^
> SyntaxError: invalid syntax.
> please explain how to remove the error.Thanks in advance

check the python version you are running with, this print format is written for py version 2.x , but for py version 3.x u need to write print statements as "print( 'Accuracy =', self.model.evaluate(x_test, y_test)[1]))" without outer quotes. or just change the python version to 2.x .

**Comment by kuruvadattatreya** [comment]
Thank you sir for the reply.after removing the error I have got another
error.
~\Anaconda3\lib\site-packages\numpy\lib\arraypad.py in pad(array,
pad_width, mode, **kwargs) 1167 """ 1168 if not
np.asarray(pad_width).dtype.kind
== 'i': -> 1169 raise TypeError('`pad_width` must be of integral type.')
1170 1171 narray = np.array(array) TypeError: `pad_width` must be of
integral type.

**Comment by hkveeranki** [comment]
Thanks for raising this up. I will try to make the code 2-3 compatible.

**Comment by hkveeranki** [comment]
@kuruvadattatreya After 8cc5188574b74419290a94511b61eed052a4faf5,  the code is python2-3 compatible. Please run now and check. If you face any problems, open a new issue.
