### ISSUE TITLE
how did you calculated the mslen for a particular db?

### ISSUE THREAD

**Issue by rishabh-kr-jain** [harry-7/speech-emotion-recognition#7]

**Comment by hkveeranki** [comment]
mslen stands for mean signal length, it is the mean of "number of frames" over all signals in database. I iterated over all the signals counted number of frames and found their mean. But I noticed that there are some outliers ( like really long signals and some really short signals, so I adjusted the mean a bit and came to the value that I finally used in the code. Does that answer your question?

**Comment by rishabh-kr-jain** [comment]
yes, thank you so much :))
