### ISSUE TITLE
 min_sample = int('9' * 10)

### ISSUE THREAD

**Issue by rishabh-kr-jain** [harry-7/speech-emotion-recognition#8]
what does this particular line stands for and how did you reached this particular value?

**Comment by hkveeranki** [comment]
That was just a huge value, that I initialised the min_sample to. Later that is anyway being caluclated again to find the minimum size of the sample. This particular piece of code is not used anywhere. So it is a like a dead code so I will remove it.

**Comment by hkveeranki** [comment]
This has been removed.

**Comment by rishabh-kr-jain** [comment]
okay :))
