### ISSUE TITLE
unable to run the code

### ISSUE THREAD

**Issue by rishabh-kr-jain** [harry-7/speech-emotion-recognition#9]
i  created the environment as per the requirements. But still i am getting an error

$ python2 mlmodel.py 1
Traceback (most recent call last):
  File "mlmodel.py", line 9, in <module>
    from . import Model
ValueError: Attempted relative import in non-package

**Comment by hkveeranki** [comment]
https://github.com/harry-7/speech-emotion-recognition#using-the-package Have a look at example.py on how to use the library. You are not using the code in the right way and that's why it is not working :). Please have the latest version of code also.

**Comment by rishabh-kr-jain** [comment]
oh , i get it now :))

**Comment by Nandy-Saran** [comment]
I am facing a similar error in github. However I tried it in Google Colab and I got the following error:
NN has no attribute called 'train'. Could you please look into the issue?
This is the Colab notebook. 
https://colab.research.google.com/drive/19zXD0GzR5-gXqoTEfZIW0PbHswdbc4ZD
